### ISSUE TITLE
Druid Circle of the Shepherd Spirit Totems effects

### ISSUE THREAD

**Issue by itteerde** [itteerde/fvttconfig#25]
Druid Circle of the Shepherd Spirit Totems effects effecting valid targets automatically would be nice.

**Comment by Taseabridge** [comment]
Progress was made on the Unicorn Totem.
The ability will automatically call the Unicorn Template when the ability is used. And all tokens within the range of the totem will become eligible for healing, which can be applied with a button click from the chat window.
After a Healing spell is cast, the "Unicorn Totem" should be "used" again in order to generate the healing chat card to apply the healing.

**Comment by Taseabridge** [comment]
There are still two remaining effects. 
Hawk Totem - Gives the caster the ability to give one person in the aura's range "Advantage" on one attack, by using their own Reaction during the ally's attack.

Bear Totem - Provides those in range of the totem 5 +  ' Druid Level' Temp. HP. Also provides all those within the aura's range advantage on Str check and saves.

**Comment by itteerde** [comment]
Requestor ChatMessage. GM, once, image.

**Comment by Taseabridge** [comment]
Unicorn Spirit complete
Bear Spirit Complete

Hawk Spirit - Uncomplete, undecided
How valuable?
Hawk spirit allows the druid to:
1. Prior to an allies attack roll, the Druid can use their reaction when an ally makes an attack to grant them advantage on the attack roll
2. Grant allies advantage on Wisdom(Perception) checks while in the aura.

**Comment by Taseabridge** [comment]
We decided to drop requestor. Will rebuild in game.
